{
 "title": "CNAPI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CNAPI instance count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of CNAPI instances" }
   ],
   "targets": [
    {
     "expr": "count(time_of_day{instance=~\"cnapi.\"})",
     "legendFormat": "instances"
    }
   ]
  },
  {
   "title": "CNAPI server count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of Servers" }
   ],
   "targets": [
    {
     "expr": "plugin_cnapi_cn_count{instance=~\"cnapi.\"}",
     "legendFormat": "servers"
    }
   ]
  },
  {
   "title": "CNAPI requests by status code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_completed{service=\"cnapi\"}[5m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "CNAPI request duration",
   "type": "graph",
   "description": "This ignores serverwaitlist* and taskwait routes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds{service=\"cnapi\",route!~\"serverwaitlist.*\",route!~\"taskwait\"}[5m])) by (le,route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "CNAPI requests per endpoint (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_completed{service=\"cnapi\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "CNAPI average handling time by endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_sum{service=\"cnapi\"}[5m])) by (route) / sum(rate(http_request_duration_seconds_count{service=\"cnapi\"}[5m])) by (route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "CNAPI cpu vs cap (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "CPU %" }
   ],
   "targets": [
    {
     "expr": "cpucap_effective_percentage{instance=~\"cnapi.\"}",
     "legendFormat": "cap"
    },
    {
     "expr": "cpucap_cur_usage_percentage{instance=~\"cnapi.\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "CNAPI load average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "load_average{instance=~\"cnapi.\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CNAPI memory vs cap (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes", "label": "DRAM" }
   ],
   "targets": [
    {
     "expr": "mem_limit{instance=~\"cnapi.\"}",
     "legendFormat": "cap"
    },
    {
     "expr": "mem_agg_usage{instance=~\"cnapi.\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "CNAPI swap vs cap (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_swap_limit{instance=~\"cnapi.\"}",
     "legendFormat": "cap"
    },
    {
     "expr": "mem_swap{instance=~\"cnapi.\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "CNAPI VFS read/write (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vfs_bytes_read_count{instance=~\"cnapi.\"}[5m])",
     "legendFormat": "bytes read"
    },
    {
     "expr": "rate(vfs_bytes_written_count{instance=~\"cnapi.\"}[5m]) * -1",
     "legendFormat": "bytes written"
    }
   ]
  },
  {
   "title": "CNAPI VFS wait/run count (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vfs_elements_run_state{instance=~\"cnapi.\"}",
     "legendFormat": "run"
    },
    {
     "expr": "vfs_elements_wait_state{instance=~\"cnapi.\"}",
     "legendFormat": "wait"
    }
   ]
  },
  {
   "title": "CNAPI established TCP connections (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tcp_current_established_connections_total{instance=~\"cnapi.\"}",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "CNAPI Network Traffic (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(net_agg_bytes_in{instance=~\"cnapi.\"}[5m])",
     "legendFormat": "bytes in"
    },
    {
     "expr": "rate(net_agg_bytes_out{instance=~\"cnapi.\"}[5m]) * -1",
     "legendFormat": "bytes out"
    }
   ]
  },
  {
   "title": "CNAPI moray requests by RPC (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fast_client_requests_completed{service=\"cnapi\"}[5m])) by (rpcMethod)",
     "legendFormat": "{{rpcMethod}}"
    }
   ]
  },
  {
   "title": "CNAPI moray latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(fast_client_request_time_ms{service=\"cnapi\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(fast_client_request_time_ms{service=\"cnapi\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(fast_client_request_time_ms{service=\"cnapi\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "CNAPI pfiles (by type)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(plugin_cnapi_pfiles) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}