{
 "title": "Global Zones",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ARC size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "arcstats_size_bytes", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Estimated NTP Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "ntp_estimated_error_seconds", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "cmon-agent requests by status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_completed{service=\"cmon-agent\"}[5m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "cmon-agent request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds{service=\"cmon-agent\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds{service=\"cmon-agent\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds{service=\"cmon-agent\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "cmon-agent collector time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(collector_time_total_seconds{service=\"cmon-agent\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(collector_time_total_seconds{service=\"cmon-agent\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(collector_time_total_seconds{service=\"cmon-agent\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "cmon-agent collector time p95",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(collector_time_seconds{service=\"cmon-agent\"}[5m])) by (le,collector))",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Number of items in cmon-agent cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cached_items{service=\"cmon-agent\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "cmon-agent cache misses/hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_get_hits_total{service=\"cmon-agent\"}[5m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(rate(cache_gets_total{service=\"cmon-agent\"}[5m]) - rate(cache_get_hits_total{service=\"cmon-agent\"}[5m]))",
     "legendFormat": "misses"
    }
   ]
  }
 ]
}