{
 "title": "Manatee",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Moray Database Queries (rows/sec)",
   "type": "graph",
   "description": "See:\n\nhttps://www.postgresql.org/docs/9.2/static/monitoring-stats.html\n\nTable 27-4. pg_stat_database View",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted[5m]))",
     "legendFormat": "deleted"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted[5m]))",
     "legendFormat": "inserted"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated[5m]))",
     "legendFormat": "updated"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched[5m]))",
     "legendFormat": "fetched"
    }
   ]
  },
  {
   "title": "Disk Reads (per second)",
   "type": "graph",
   "description": "See:\n\nhttps://www.postgresql.org/docs/9.2/static/monitoring-stats.html\n\nTable 27-4. pg_stat_database View",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_read[5m])) by (backend)",
     "legendFormat": "{{backend}} reads"
    },
    {
     "expr": "sum(rate(pg_stat_database_blks_hit[5m])) by (backend)",
     "legendFormat": "{{backend}} cached reads"
    }
   ]
  },
  {
   "title": "User Tables Query Time (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_user_tables_querytime_ms[5m]) / 1000) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "User Table Stats (per second)",
   "type": "graph",
   "description": "See: \n\nhttps://www.postgresql.org/docs/9.2/static/monitoring-stats.html\n\nTable 27-5. pg_stat_all_tables View",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_user_tables_n_tup_ins[5m]))",
     "legendFormat": "insert"
    },
    {
     "expr": "sum(rate(pg_stat_user_tables_n_tup_del[5m]))",
     "legendFormat": "delete"
    },
    {
     "expr": "sum(rate(pg_stat_user_tables_n_tup_upd[5m]))",
     "legendFormat": "update"
    },
    {
     "expr": "sum(rate(pg_stat_user_tables_n_tup_hot_upd[5m]))",
     "legendFormat": "hot_update"
    }
   ]
  },
  {
   "title": "Connections to Manatee (moray DB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_connections{state=\"active\",datname=\"moray\"}",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Manatee Transactions Committed (tx/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pg_stat_database_xact_commit[5m])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  }
 ]
}