{
 "title": "Moray",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Moray RPCs/sec by Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fast_requests_completed{instance=~\"moray.\"}[5m])) by (rpcMethod)",
     "legendFormat": "{{rpcMethod}}"
    }
   ]
  },
  {
   "title": "moray0 RPCs/sec by Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fast_requests_completed{instance=~\"moray0\"}[5m])) by (rpcMethod)",
     "legendFormat": "{{rpcMethod}}"
    }
   ]
  },
  {
   "title": "moray1 RPCs/sec by Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fast_requests_completed{instance=~\"moray1\"}[5m])) by (rpcMethod)",
     "legendFormat": "{{rpcMethod}}"
    }
   ]
  },
  {
   "title": "moray2 RPCs/sec by Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fast_requests_completed{instance=~\"moray2\"}[5m])) by (rpcMethod)",
     "legendFormat": "{{rpcMethod}}"
    }
   ]
  }
 ]
}