{
 "title": "NAPI",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NAPI uptime",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - nodejs_process_start_time_seconds{service=\"napi\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NAPI process start time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "dateTimeAsUS" }
   ],
   "targets": [
    {
     "expr": "nodejs_process_start_time_seconds{service=\"napi\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nodejs eventloop tick count (per \"500 ms\")",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_max_tick_count{service='napi'}",
     "legendFormat": "max"
    },
    {
     "expr": "nodejs_eventloop_min_tick_count{service='napi'}",
     "legendFormat": "min"
    },
    {
     "expr": "irate(nodejs_eventloop_tick_count_total{service='napi'}[5m]) / 2",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "node eventloop lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_max_lag_seconds{service=\"napi\"}",
     "legendFormat": "maxLag"
    },
    {
     "expr": "nodejs_eventloop_min_lag_seconds{service=\"napi\"}",
     "legendFormat": "minLag"
    },
    {
     "expr": "irate(nodejs_eventloop_lag_seconds_total{service=\"napi\"}[5m]) / irate(nodejs_eventloop_samples_total{service=\"napi\"}[5m])",
     "legendFormat": "avgLag"
    }
   ]
  },
  {
   "title": "node eventloop time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_max_time_seconds{service=\"napi\"}",
     "legendFormat": "maxTime"
    },
    {
     "expr": "nodejs_eventloop_min_time_seconds{service=\"napi\"}",
     "legendFormat": "minTime"
    },
    {
     "expr": "irate(nodejs_eventloop_time_seconds_total{service=\"napi\"}[5m]) / irate(nodejs_eventloop_tick_count_total{service=\"napi\"}[5m])",
     "legendFormat": "avgTime"
    }
   ]
  },
  {
   "title": "NAPI GC count (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_execution_count_total{service=\"napi\"}[5m])",
     "legendFormat": "{{instance}}-{{gcType}}"
    }
   ]
  },
  {
   "title": "NAPI GC pause time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_pause_seconds_total{service=\"napi\"}[5m])",
     "legendFormat": "{{instance}}-{{gcType}}"
    }
   ]
  },
  {
   "title": "node memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_memory_external_bytes{service=\"napi\"}",
     "legendFormat": "external"
    },
    {
     "expr": "nodejs_memory_heapTotal_bytes{service=\"napi\"}",
     "legendFormat": "heapTotal"
    },
    {
     "expr": "nodejs_memory_heapUsed_bytes{service=\"napi\"}",
     "legendFormat": "heapUsed"
    },
    {
     "expr": "nodejs_memory_rss_bytes{service=\"napi\"}",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "v8 memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_V8_total_heap_size_bytes{service=\"napi\"}",
     "legendFormat": "V8 total heap"
    },
    {
     "expr": "nodejs_V8_total_available_size_bytes{service=\"napi\"}",
     "legendFormat": "V8 available"
    },
    {
     "expr": "nodejs_V8_heap_size_limit_bytes{service=\"napi\"}",
     "legendFormat": "V8 limit"
    },
    {
     "expr": "nodejs_V8_heap_size_executable_bytes{service=\"napi\"}",
     "legendFormat": "V8 executable"
    },
    {
     "expr": "nodejs_V8_total_physical_size_bytes{service=\"napi\"}",
     "legendFormat": "V8 physical size"
    },
    {
     "expr": "nodejs_V8_used_heap_size_bytes{service=\"napi\"}",
     "legendFormat": "V8 used"
    }
   ]
  },
  {
   "title": "node activeRequests/activeHandles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_requests_count{service=\"napi\"}",
     "legendFormat": "{{instance}}-activeRequests"
    },
    {
     "expr": "nodejs_active_handles_count{service=\"napi\"}",
     "legendFormat": "{{instance}}-activeHandles"
    }
   ]
  },
  {
   "title": "CNAPI node CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_system_cpu_seconds_total{service=\"napi\"}[5m])",
     "legendFormat": "{{instance}}-system"
    },
    {
     "expr": "rate(nodejs_user_cpu_seconds_total{service=\"napi\"}[5m])",
     "legendFormat": "{{instance}}-user"
    }
   ]
  },
  {
   "title": "NAPI requests by status code (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_completed{service=\"napi\"}[5m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "NAPI request duration (p95)",
   "type": "graph",
   "description": "This ignores serverwaitlist* and taskwait routes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds{service=\"napi\",route!~\"serverwaitlist.*\",route!~\"taskwait\"}[5m])) by (le,route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "NAPI requests per endpoint (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_completed{service=\"napi\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "NAPI average handling time by endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_sum{service=\"napi\"}[5m])) by (route) / sum(rate(http_request_duration_seconds_count{service=\"napi\"}[5m])) by (route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "NAPI moray requests by RPC (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fast_client_requests_completed{service=\"napi\"}[5m])) by (rpcMethod)",
     "legendFormat": "{{rpcMethod}}"
    }
   ]
  },
  {
   "title": "NAPI moray latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(fast_client_request_time_ms{service=\"napi\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(fast_client_request_time_ms{service=\"napi\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(fast_client_request_time_ms{service=\"napi\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "NAPI cpu vs cap (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "CPU %" }
   ],
   "targets": [
    {
     "expr": "cpucap_effective_percentage{instance=~\"napi.\"}",
     "legendFormat": "cap"
    },
    {
     "expr": "cpucap_cur_usage_percentage{instance=~\"napi.\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "NAPI load average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "load_average{instance=~\"napi.\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NAPI memory vs cap (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "bytes", "label": "DRAM" }
   ],
   "targets": [
    {
     "expr": "mem_limit{instance=~\"napi.\"}",
     "legendFormat": "cap"
    },
    {
     "expr": "mem_agg_usage{instance=~\"napi.\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "NAPI swap vs cap (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_swap_limit{instance=~\"napi.\"}",
     "legendFormat": "cap"
    },
    {
     "expr": "mem_swap{instance=~\"napi.\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "NAPI VFS read/write (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vfs_bytes_read_count{instance=~\"napi.\"}[5m])",
     "legendFormat": "bytes read"
    },
    {
     "expr": "rate(vfs_bytes_written_count{instance=~\"napi.\"}[5m]) * -1",
     "legendFormat": "bytes written"
    }
   ]
  },
  {
   "title": "NAPI VFS wait/run count (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vfs_elements_run_state{instance=~\"napi.\"}",
     "legendFormat": "run"
    },
    {
     "expr": "vfs_elements_wait_state{instance=~\"napi.\"}",
     "legendFormat": "wait"
    }
   ]
  },
  {
   "title": "NAPI TCP listen drops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tcp_listen_drop_count{instance=~\"napi.\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NAPI established TCP connections (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tcp_current_established_connections_total{instance=~\"napi.\"}",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "NAPI Network Traffic (zone)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(net_agg_bytes_in{instance=~\"napi.\"}[5m])",
     "legendFormat": "bytes in"
    },
    {
     "expr": "rate(net_agg_bytes_out{instance=~\"napi.\"}[5m]) * -1",
     "legendFormat": "bytes out"
    }
   ]
  }
 ]
}