{
 "title": "Triton Service Routes",
 "description": "Triton Service Routes",
 "tags": [ "triton" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datacenter", "label": "Datacenter", "query": "http_request_duration_seconds" },
   {
    "name": "triton_service",
    "label": "Triton Service",
    "query": "http_request_duration_seconds{job=~\"admin_.*\"}"
   },
   {
    "name": "route",
    "label": "Route",
    "query": "http_request_duration_seconds{job=~\"admin_.*\",alias=~\"[[triton_service]][0-9]+\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(time_of_day{alias=~\"[[triton_service:regex]].\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "(user + system time)",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((increase(cpu_sys_usage{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) + increase(cpu_user_usage{alias=~\"[[triton_service:regex]][0-9]+\"}[60s])) / 60000000000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_agg_usage{alias=~\"[[triton_service:regex]][0-9]+\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_completed{alias=~\"[[triton_service:regex]][0-9]+\"}[5m]))by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Overall Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_sum{service=\"[[triton_service]]\"}[5m]))  / sum(rate(http_request_duration_seconds_count{service=\"[[triton_service]]\"}[5m])) )",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds{service=\"[[triton_service]]\"}[1m])) by (le))",
     "legendFormat": "50p"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds{service=\"[[triton_service]]\"}[1m])) by (le))",
     "legendFormat": "95p"
    }
   ]
  },
  { "title": "[[triton_service]]: [[route]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "route" },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_completed{service=~\"[[triton_service]]\",route=\"[[route]]\",status_code!~\"5.+\"}[5m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(http_requests_completed{service=~\"[[triton_service]]\",route=\"[[route]]\",status_code=~\"5.+\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_sum{service=\"[[triton_service]]\",route=\"[[route]]\"}[5m])) / sum(rate(http_request_duration_seconds_count{service=\"[[triton_service]]\",route=\"[[route]]\"}[5m])))",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds{service=\"[[triton_service]]\",route=\"[[route]]\"}[1m])) by (le))",
     "legendFormat": "50p"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds{service=\"[[triton_service]]\",route=\"[[route]]\"}[1m])) by (le))",
     "legendFormat": "95p"
    }
   ]
  }
 ]
}