{
 "title": "Triton Service HTTP Overview",
 "description": "Triton Service HTTP Overview",
 "tags": [ "triton" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datacenter", "label": "Datacenter", "query": "http_request_duration_seconds" },
   {
    "name": "triton_service",
    "label": "Triton Service",
    "query": "http_request_duration_seconds{job=~\"admin_.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(time_of_day{instance=~\"[[triton_service:regex]].\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "(user + system time)",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((increase(cpu_sys_usage{instance=~\"[[triton_service:regex]][0-9]+\"}[60s]) + increase(cpu_user_usage{instance=~\"[[triton_service:regex]][0-9]+\"}[60s])) / 60000000000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_agg_usage{instance=~\"[[triton_service:regex]][0-9]+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_completed{instance=~\"[[triton_service:regex]][0-9]+\"}[5m]))by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "95p by service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds{service=~\"[[triton_service:regex]]\"}[1m])) by (le,service))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Errors by service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_completed{status_code=~\"5.+\",instance=~\"[[triton_service:regex]][0-9]+\"}[5m]))by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "requests by status code",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_completed{instance=~\"[[triton_service:regex]][0-9]+\"}[5m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "95p by status code",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds{service=~\"[[triton_service:regex]]\"}[1m])) by (le,status_code))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "requests by route",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_completed{instance=~\"[[triton_service:regex]][0-9]+\"}[5m])) by (service,route)",
     "legendFormat": "{{service}}: {{route}}"
    }
   ]
  },
  {
   "title": "95p  by route",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds{service=~\"[[triton_service:regex]]\"}[1m])) by (le,service,route))",
     "legendFormat": "{{service}}: {{route}}"
    }
   ]
  },
  {
   "title": "Errors  by route",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_completed{status_code=~\"5.+\",instance=~\"[[triton_service:regex]][0-9]+\"}[5m]))by (service,route)",
     "legendFormat": "{{service}}: {{route}}"
    }
   ]
  }
 ]
}